name: Build The System Android v11
on:
  push:
    branches: [ "android-v11-stable" ]
    paths-ignore: [ "android-builds/**" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - name: Install Android SDK
        run: yes | sdkmanager "platforms;android-36" "build-tools;36.0.0"
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'
      - name: Build unsigned release APK
        working-directory: android-v10-4
        run: gradle :app:assembleRelease --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: TheSystem-v11.0-unsigned-release
          path: |
            android-v10-4/app/build/outputs/apk/release/app-release-unsigned.apk
            /usr/local/lib/android/sdk/build-tools/36.0.0/lib/apksigner.jar
